# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k_garden_id', models.IntegerField()),
                ('kid_id', models.IntegerField()),
                ('kid_name', models.CharField(blank=True, max_length=255, null=True)),
                ('class_id', models.IntegerField()),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('relativity', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'linked_contacts',
            },
        ),
    ]
