# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_auto_20170314_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendas',
            options={},
        ),
    ]
